### PR TITLE
feat: build card-store UI for deployment (WIP)

### PR DESCRIPTION
**Pull request by dckc**
Looks like a simple `yarn build` in a netlify depoly won't cut it. MF suggested doing the `agoric install` part in a github action, so let's try this out.

ref #10

### CODE REVIEW

**Comment by katelynsills** [comment]
@dckc, you might be doing this already, but if we could try deploying from https://github.com/Agoric/dapp-card-store/pull/18, that would be the latest version. I haven't merged it into master yet because it has linting issues and i've been focused on dapp-token-economy

**Comment by dckc** [comment]
No, I wasn't already doing that.. I'm rebasing to see if I can get it into this branch.

Once this PR lands, each PR after that will get its own deploy preview.

But only updates to `main` will deploy to https://card-store.agoric.app/

**Comment by katelynsills** [comment]
> Once this PR lands, each PR after that will get its own deploy preview.
> But only updates to `main` will deploy to https://card-store.agoric.app/

Ok, great, I'll work on getting https://github.com/Agoric/dapp-card-store/pull/18 into `main`

**Review by dckc — COMMENTED** [review]
LGTM

(I created this PR so github won't let me Approve)

**Pull request merged**
