### PR TITLE
Update App.js

### PR DESCRIPTION
**Pull request by zarutian**
Using now the newly added sellItemsPublicFacet.getAvailableItemsNotifier()

Dependent on pull-request [agoric-sdk #3123](https://github.com/Agoric/agoric-sdk/pull/3123)

### CODE REVIEW

**Comment by zarutian** [comment]
This resolves #19

**Comment by zarutian** [comment]
Paging @katelynsills for review as [agoric-sdk #3123](https://github.com/Agoric/agoric-sdk/pull/3123) has been merged.

**Comment by katelynsills** [comment]
Thanks @zarutian! I pushed up a commit that uses an async iterable. That way, we don't have to use `setInterval` at all. I have not done the manual testing for this change yet. Can you help me confirm that it works? It also looks like my commit needs linting.

**Comment by katelynsills** [comment]
Hi @zarutian, can I help at all on this PR?

**Comment by zarutian** [comment]
@katelynsills  yeah, I was trying to remove node version12 as one of the runtimes tested as only version 14 and higher is what agoric-sdk supports now.

**Comment by katelynsills** [comment]
Hi @zarutian, luckily, the changes that @kriskowal made on `main` will fix the Node 12 issue for us. I went ahead and did some testing and realized that the `for await` loop needed to be moved into a location where the publicFacet was already defined. Apart from an issue where the user does not have any RUN (https://github.com/Agoric/agoric-sdk/issues/3266) I think we are ready to merge this.

Thank you so much for all your work on this. It's awesome to see so much progress.

**Pull request merged**
